# Require trusty for now as it has a more recent version of autoconf
sudo: required
dist: trusty
language: c

compiler:
    - gcc
    - clang

os:
    - linux
    - osx


addons:
    apt:
        packages:
            - autoconf
            - automake
            - libtool
            - m4
            - libusb-1.0-dev
        sources:
            - ubuntu-toolchain-r-test

script:
    - ./autogen.sh && make -j4
